fix: Set bash as the interpretter for bash-hook command
getsentry/sentry-cli pull request #1262
Opened 2022-06-27 13:01 UTC by kamilogorek

Shell script produced by `bash-hook` was missing a shebang, which caused it to be executed by `sh` in some environments. And because `sh` has no process substitution (https://www.shellcheck.net/wiki/SC3001) it failed with a syntax error.

Fixes https://github.com/getsentry/sentry-cli/issues/1260

2022-06-27 13:38 UTC, mitsuhiko requested changes
that won't work since you need to source it in bash. It might be better to detect non bash use and fail quickly.

2022-06-27 13:59 UTC, kamilogorek commented
@mitsuhiko not sure what's reliable way of detecting used interpreter

2022-07-05 13:43 UTC, armenzg requested changes
Checking the value of `$SHELL` is sufficient.

2022-07-05 14:18 UTC, kamilogorek commented
How would `$SHELL` tell you that you are not using `sh`? 🤔

2022-12-06 13:36 UTC, kamilogorek commented
This wont work, so cleaning it up for now.

2022-12-06 13:36 UTC, closed without merging