feat(monitors): Pass SENTRY_TRACE_ID down execution path
getsentry/sentry-cli pull request #1441
Opened 2023-01-26 21:01 UTC by evanpurkhiser

This adds `SENTRY_TRACE_ID` to the environ of the executing command.

This is in support of https://github.com/getsentry/sentry/issues/43647
and will allow SDKs embedded in the executing command to associate the
monitor checkin to any events produced by the SDK.

This is the second part of #1438

2023-01-27 16:33 UTC, kamilogorek requested changes

2023-01-27 16:33 UTC, kamilogorek commented on src/commands/monitors/run.rs
> +
```suggestion
    // Inherit outer SENTRY_TRACE_ID if present
    let trace_id = env::var_os("SENTRY_TRACE_ID").unwrap_or_else(|| Uuid::new_v4().simple().to_string())
    p.env("SENTRY_TRACE_ID", trace_id);

```

2023-01-27 16:33 UTC, kamilogorek commented on src/commands/monitors/run.rs
> +
```suggestion
```

2023-01-27 16:33 UTC, kamilogorek commented on src/commands/monitors/run.rs
> +
Please check if it compiles correctly, as I wrote it directly in a suggestion 😅

2023-01-27 16:34 UTC, kamilogorek commented on src/commands/monitors/run.rs
> +
Also run `make lint` and `make format`.

2023-01-30 08:47 UTC, kamilogorek approved these changes
I'm doing a release, so will allow myself to merge that one

2023-01-30 09:03 UTC, merged

2023-01-31 00:39 UTC, evanpurkhiser commented
Oh wait, I wasn't ready to merge this hahaha

2023-01-31 09:04 UTC, kamilogorek commented
Oh, then it should be a draft 🌝 but no harm done, as it's a self-contained change and will not break anything.