Add support for `SENTRY_RELEASE` in bash-hook
getsentry/sentry-cli pull request #1720
Opened 2023-08-27 09:40 UTC by boozec

This PR adds support for `SENTRY_RELEASE` variable in the `bash-hook` command.
It adds `--release` argument in the command but the environment variable is
still available, so it checks the value from env first.

2023-08-27 10:02 UTC, boozec commented
Clippy lint fails for some old sources, should I fix them anyway?

PS: on local instance it does not fail :\

2023-08-28 07:38 UTC, kamilogorek commented
It fails because 4 days ago, Rust `1.72.0` was released, and as always, Clippy came with new defaults 😄

2023-08-28 08:10 UTC, boozec commented
Ops, I missed the update to `1.72.0`, thank you :)

2023-08-28 08:35 UTC, kamilogorek requested changes

2023-08-28 08:35 UTC, kamilogorek commented on src/commands/bash_hook.rs
> +        }),
```suggestion
        release: release.or(detect_release_name().ok()).map(Into::into),
```

2023-08-28 08:35 UTC, kamilogorek commented on src/commands/bash_hook.rs
> +    };
```suggestion
    let release = Config::current().get_release(matches).ok();
```

2023-08-28 08:35 UTC, kamilogorek commented on src/commands/bash_hook.rs
> +        None => script.replace("___SENTRY_RELEASE___", ""),
```suggestion
            " ___SENTRY_RELEASE___",
            format!(" --release \"{}\"", release).as_str(),
        ),
        None => script.replace(" ___SENTRY_RELEASE___", ""),
```

2023-08-28 08:35 UTC, kamilogorek commented on src/bashsupport.sh
> +  export SENTRY_LAST_EVENT=$(___SENTRY_CLI___ bash-hook --send-event --traceback "$_SENTRY_TRACEBACK_FILE" ___SENTRY_TAGS______SENTRY_RELEASE___ --log "$_SENTRY_LOG_FILE" ___SENTRY_NO_ENVIRON___)
```suggestion
  export SENTRY_LAST_EVENT=$(___SENTRY_CLI___ bash-hook --send-event --traceback "$_SENTRY_TRACEBACK_FILE" ___SENTRY_TAGS___ ___SENTRY_RELEASE___ --log "$_SENTRY_LOG_FILE" ___SENTRY_NO_ENVIRON___)
```

2023-08-28 08:37 UTC, kamilogorek requested changes

2023-08-28 08:37 UTC, kamilogorek commented on src/commands/bash_hook.rs
> +                .value_name("RELEASE_VERSION")
```suggestion
                .value_name("RELEASE")
```

2023-08-28 08:37 UTC, kamilogorek commented on tests/integration/_cases/bash_hook/bash_hook-help.trycmd
> +      --release <RELEASE_VERSION>  Define release version for the event.
```suggestion
      --release <RELEASE>  Define release version for the event.
```

2023-08-28 08:37 UTC, kamilogorek commented on src/commands/bash_hook.rs
> +        }),
Simplified

2023-08-28 08:37 UTC, kamilogorek commented on src/commands/bash_hook.rs
> +    };
Simplified

2023-08-28 08:37 UTC, kamilogorek commented on src/commands/bash_hook.rs
> +        None => script.replace("___SENTRY_RELEASE___", ""),
Better redability for `bashsupport.sh`

2023-08-28 08:37 UTC, kamilogorek commented on src/commands/bash_hook.rs
> +                .value_name("RELEASE_VERSION")
Consistency with other `--release` flags.

2023-08-28 08:37 UTC, kamilogorek commented on tests/integration/_cases/bash_hook/bash_hook-help.trycmd
> +      --release <RELEASE_VERSION>  Define release version for the event.
Consistency with other `--release` flags.

2023-08-28 08:47 UTC, boozec commented
Thank you for all the simplification tips :)

2023-08-28 10:30 UTC, merged