fix(rn): Upload root bundle source map for ram bundles
getsentry/sentry-cli pull request #1743
Opened 2023-09-14 12:55 UTC by krystofwoldrich

- fixes https://github.com/getsentry/sentry-cli/issues/1741

`rust-sourcemap` package only parses modules but doesn't include the root bundle file therefore also doesn't include it's source map.

2023-09-14 15:28 UTC, loewenheim requested changes

2023-09-14 15:28 UTC, loewenheim commented on src/utils/sourcemaps.rs
> +        if let Some(sourcemap_source) = self.sources.get(&sourcemap_url) {
You need to check the presence of this file earlier anyway. I would suggest replacing the block starting at line 532 with
```rust
        let Some(sourcemap_source) = self.sources.get(&sourcemap_url) else {
            warn!(
                "Cannot find the sourcemap for the RAM bundle using the URL: {}, skipping",
                sourcemap_url
            );
            return Ok(());
        };
        let sourcemap_content = &sourcemap_source.contents;
```
and removing this check.

2023-09-15 09:16 UTC, krystofwoldrich commented on src/utils/sourcemaps.rs
> +                if let Some(index_section) = index_section.get_sourcemap() {
I like the `and_then`. Thank you.

2023-09-15 11:24 UTC, krystofwoldrich commented
@loewenheim Thank you for the suggestion, this is much cleaner.

2023-09-15 11:41 UTC, loewenheim approved these changes
Looks good now

2023-09-15 11:42 UTC, merged