feat(js): allows the user to specify multiple projects for a release
getsentry/sentry-cli pull request #842
Opened 2020-10-07 20:18 UTC by scefali

This PR enables setting multiple projects when creating a release with the JS wrapper for the CLI. It adds a new optional parameter to the `new` function called `options` which has a `projects` field which is an array of strings. Example:

```
cli.releases.new('my-version', { projects: ['proj-a', 'proj-b'] });
```

Becomes:
```
sentry-cli releases new -p proj-a -p proj-b my-version
```
CLI docs: https://docs.sentry.io/product/releases/#using-the-cli

2020-10-13 09:20 UTC, kamilogorek commented
If we want to make it future-proof, can we rework it in a way, where constructor will hold `baseArgs`, which include top-level flags and then it's reused everywhere? Something like

```js
constructor(options) {
  this.baseArgs = ['release'].concat(getCommandFlagsFromOptions(options));
}

// create map of name/flag so we can extend it later
const commandFlags = {
  'projects': '-p'
}

function getCommandFlagsFromOptions(options) {
  const flags = [];
  Object.keys(commandFlags).forEach(key => {
    const option = options[key];
    if (!option) return;
    (Array.isArray(option) ? option : [option]).forEach(option => {
      flags.push(commandFlags[key]);
      flags.push(options[key]);
    });
  });
  return flags;
}

// Later in the command

new(release, options) {
  const args = this.baseArgs.concat(['new', release, helper.getProjectFlagsFromOptions(options)]);
  return this.execute(args, null);
}
```

(this `getCommandFlagsFromOptions` part is actually working code (i guess) so you can copy-paste it :P)

2020-10-13 16:47 UTC, scefali commented
@kamilogorek I think this approach would be good if we didn't have the problem with the source maps command not being able to take multiple projects. But since it can't, you'd need to make a new instance of releases when you upload source maps which makes it pretty clunky. IMO, better to supply the arguments for each function individually until the CLI can accommodate multiple projects with upload commits.

2020-10-27 15:06 UTC, kamilogorek requested changes

2020-10-28 10:14 UTC, kamilogorek approved these changes

2020-10-29 12:27 UTC, merged

2020-12-02 14:25 UTC, MrGWest commented
How is `finalize` supposed to work? Our builds used to work, but now `--project` is required it seems, but `-p proj-a -p proj-b` is failing with `The argument '--project <PROJECT>' was provided more than once, but cannot be used multiple times`.

2020-12-02 15:05 UTC, kamilogorek commented
@MrGWest did it happened using `1.60.0` by any chance? If so, please see https://github.com/getsentry/sentry-cli/issues/868

2020-12-02 17:11 UTC, scefali commented
@MrGWest Some of the release actions don't actually support using multiple projects, unfortunately (source maps being one of them). This is a limitation in the CLI core rather than the JS wrapper.

2021-03-12 11:22 UTC, guillaume86 commented
This is really confusing in the documentation (and convoluted to use), from https://docs.sentry.io/product/cli/releases/

> Release Management
> The sentry-cli tool can be used for release management on Sentry. It allows you to create, edit and delete releases as well as upload release artifacts for them. Note that **releases are global per organization**. If you want the releases in different projects to be treated as separate entities, make the version name unique across the organization. For example, if you have projectA and projectB that share version numbers, you can name the releases projectA-1.0 and projectB-1.0 respectively.
> 
> **Because releases work on projects you will need to specify the organization and project you are working with**. For more information about this refer to Working with Projects.

The two statements seem to contradict each other. My preferred solution would be to never specify a project when using the release commands (append project name to release name if needed) and let sentry auto link releases to projects with events data.