[Fix] Allow to define a custom version for source-maps upload
getsentry/sentry-cli pull request #967
Opened 2021-05-29 10:22 UTC by retyui

Fix: https://github.com/getsentry/sentry-react-native/issues/1229

2021-05-29 12:44 UTC, jennmueng reviewed
Again, thanks for this! Let's call it `SENTRY_RELEASE` and `SENTRY_DIST`. We would also need the dist to be configurable via setting the `SENTRY_DIST` environment variable too and this should be good to go!

cc @bruno-garcia

2021-05-29 12:44 UTC, jennmueng commented on src/commands/react_native_xcode.rs
> +        let release_name = env::var("SENTRY_RELEASE_NAME").unwrap_or(default_release_name);
```suggestion
        let release_name = env::var("SENTRY_RELEASE").unwrap_or(default_release_name);
```
Let's call it `SENTRY_RELEASE`.

2021-05-29 19:30 UTC, retyui commented on src/commands/react_native_xcode.rs
> +        let release_name = env::var("SENTRY_RELEASE_NAME").unwrap_or(default_release_name);
done

2021-05-31 11:12 UTC, jennmueng commented on src/commands/react_native_xcode.rs
> +
```suggestion
```
Test failed due to extra line break

2021-06-01 10:21 UTC, retyui commented
Test for macOS failed (but Linux and Windows test passed successfully) is it ok?

2021-06-01 21:27 UTC, bruno-garcia reviewed
Do we have any tests that validate this behavior?
@kamilogorek might have thoughts here though

2021-06-02 15:42 UTC, jennmueng commented
@retyui The Xcode script would only be run on macOS, this means it does not work. Can you verify that it works locally?

2021-06-02 16:20 UTC, retyui commented
>  Can you verify that it works locally?


I will try)

1) Build `cargo build --release --locked --target=x86_64-apple-darwin`
2) Copy `target/x86_64-apple-darwin/release/sentry-cli` to `node_modules/@sentry/cli/sentry-cli`
3) Store in repo `git add -f node_modules/@sentry/cli/sentry-cli ; git commit`
4) Update package.json (to use binary from repo) `"postinstall": "git checkout -f -- :/node_modules"`
5) Push to trigger build on CI


^^^^ Could you please verify that I build binary it correctly? @jennmueng

2021-06-02 20:13 UTC, retyui commented
Seems it works as expected

```sh
export SENTRY_RELEASE=1.22.333
```

<img width="1047" alt="Снимок экрана 2021-06-02 в 23 11 17" src="https://user-images.githubusercontent.com/4661784/120546006-051ca080-c3f8-11eb-91e0-f9fca10ecfac.png">

2021-06-03 08:54 UTC, retyui commented
I added a small fix to handle `SENTRY_DIST` env


Now it works fine

```
export SENTRY_DIST=777
```

![image](https://user-images.githubusercontent.com/4661784/120616852-3e89f600-c462-11eb-96d7-b39fcf634612.png)

2021-06-03 08:55 UTC, retyui commented
@bruno-garcia @jennmueng cc

2021-06-07 09:57 UTC, kamilogorek commented
Instead of using env vars, this PR should add a flag called `release` which can be used instead. This way, we'll make the experience inline with the one we already have for Gradle. Also overriding `dist` is not necessary, as we already do have `--dist` flag that you can use.

2021-06-07 10:19 UTC, retyui commented
> Also overriding dist is not necessary, as we already do have --dist flag that you can use.

You have to understand that CLI script will be run by the build phase "Bundle React Native code and images". 
 `../node_modules/@sentry/cli/bin/sentry-cli react-native xcode` in the xCode

And to define `--dist` need to path that script or use env that I propose to do

2021-06-07 11:27 UTC, kamilogorek requested changes
In this case, flags should always have precedence over env variables. Because of that, `SENTRY_DIST` should be applied only if `--dist` is absent.

2021-06-07 11:27 UTC, kamilogorek commented on src/commands/react_native_xcode.rs
> +        let release_name = env::var("SENTRY_RELEASE").unwrap_or(default_release_name);
```suggestion
        let dist = env::var("SENTRY_DIST").unwrap_or(plist.build().to_string());
        let release_name = env::var("SENTRY_RELEASE").unwrap_or(format!("{}@{}+{}", plist.bundle_id(), plist.version(), dist));
```

2021-06-07 11:27 UTC, kamilogorek commented on src/commands/react_native_xcode.rs
> +                    dist: Some(&default_dist),
```suggestion
                    dist: Some(&dist),
```

2021-06-07 11:27 UTC, kamilogorek commented on src/commands/react_native_xcode.rs
> +                        dist: Some(&env::var("SENTRY_DIST").unwrap_or(dist.to_string())),
```suggestion
                        dist: Some(dist),
```

2021-06-07 11:27 UTC, kamilogorek commented on src/commands/react_native_xcode.rs
> +        let release_name = env::var("SENTRY_RELEASE").unwrap_or(default_release_name);
This will probably fail formatting :3

2021-06-07 11:48 UTC, kamilogorek approved these changes

2021-06-07 11:50 UTC, kamilogorek commented
That's what I thought. Thanks `rustfmt` :S Looks good, will merge once formatted is happy.

2021-06-07 12:05 UTC, retyui commented
@kamilogorek seems it needs to start CI manually

2021-06-07 12:53 UTC, merged